import React, { useState } from "react";
import { Share2, Download, FileText, Loader2, Mail, MoreHorizontal } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { jsPDF } from "jspdf";
import { format } from "date-fns";

function buildPlainText(session, data) {
  const lines = [];
  const title = session.title || "Session Minutes";
  const date = session.created_date ? format(new Date(session.created_date), "MMMM d, yyyy 'at' h:mm a") : "";

  lines.push(title.toUpperCase());
  if (date) lines.push(date);
  lines.push("=".repeat(48));

  if (data?.executive_summary?.length) {
    lines.push("\n🧾 EXECUTIVE SUMMARY");
    data.executive_summary.forEach(b => lines.push(`  • ${b}`));
  }
  if (data?.key_discussions?.length) {
    lines.push("\n💬 KEY DISCUSSIONS");
    data.key_discussions.forEach(t => {
      lines.push(`\n  🔹 ${t.title}`);
      t.points?.forEach(p => lines.push(`    • ${p}`));
    });
  }
  if (data?.decisions?.length) {
    lines.push("\n⚡ DECISIONS & AGREEMENTS");
    data.decisions.forEach(d => lines.push(`  • ${d}`));
  }
  if (data?.action_items?.length) {
    lines.push("\n✅ ACTION ITEMS");
    data.action_items.forEach((a, i) => {
      lines.push(`\n  Action ${i + 1}`);
      lines.push(`  Task: ${a.task}`);
      lines.push(`  Owner: ${a.owner || "Unassigned"}`);
      lines.push(`  Deadline: ${a.deadline || "TBD"}`);
      lines.push(`  Priority: ${a.priority}`);
    });
  }
  if (data?.next_steps?.length) {
    lines.push("\n🔜 NEXT STEPS");
    data.next_steps.forEach(s => lines.push(`  • ${s}`));
  }
  if (data?.risks?.length) {
    lines.push("\n⚠️ RISKS & GAPS");
    data.risks.forEach(r => lines.push(`  • ${r}`));
  }
  if (data?.ai_insights?.length) {
    lines.push("\n💡 AI INSIGHTS");
    data.ai_insights.forEach(i => lines.push(`  • ${i}`));
  }

  lines.push("\n" + "=".repeat(48));
  lines.push("Generated by SILO");
  return lines.join("\n");
}

function addPdfSection(doc, emoji, title, yRef, pageH, margin, lineH, addLine) {
  if (yRef.y + 12 > pageH - 20) { doc.addPage(); yRef.y = margin; }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(120, 100, 200);
  addLine(`${emoji}  ${title.toUpperCase()}`);
  doc.setTextColor(50, 50, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
}

export default function ExportShare({ session, summaryData }) {
  const [loading, setLoading] = useState(null);

  const plainText = buildPlainText(session, summaryData);

  const handleDownloadText = () => {
    const blob = new Blob([plainText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${session.title || "minutes"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = () => {
    setLoading("pdf");
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const margin = 40;
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const maxW = pageW - margin * 2;
    const lineH = 14;
    const yRef = { y: margin };

    const addLine = (text, indent = 0) => {
      const lines = doc.splitTextToSize(text, maxW - indent);
      lines.forEach(line => {
        if (yRef.y + lineH > pageH - 20) { doc.addPage(); yRef.y = margin; }
        doc.text(line, margin + indent, yRef.y);
        yRef.y += lineH;
      });
    };

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(20, 20, 20);
    addLine(session.title || "Session Minutes");

    // Date
    if (session.created_date) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(130, 130, 130);
      addLine(format(new Date(session.created_date), "MMMM d, yyyy 'at' h:mm a"));
    }

    // Divider
    yRef.y += 6;
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, yRef.y, pageW - margin, yRef.y);
    yRef.y += 12;

    const data = summaryData;

    if (data?.executive_summary?.length) {
      addPdfSection(doc, "🧾", "Executive Summary", yRef, pageH, margin, lineH, addLine);
      data.executive_summary.forEach(b => { doc.setTextColor(50,50,50); addLine(`• ${b}`, 8); });
      yRef.y += 8;
    }
    if (data?.key_discussions?.length) {
      addPdfSection(doc, "💬", "Key Discussions", yRef, pageH, margin, lineH, addLine);
      data.key_discussions.forEach(t => {
        doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(80,60,160);
        addLine(`🔹 ${t.title}`, 8);
        doc.setFont("helvetica", "normal"); doc.setTextColor(50,50,50);
        t.points?.forEach(p => addLine(`• ${p}`, 16));
        yRef.y += 4;
      });
      yRef.y += 4;
    }
    if (data?.decisions?.length) {
      addPdfSection(doc, "⚡", "Decisions & Agreements", yRef, pageH, margin, lineH, addLine);
      data.decisions.forEach(d => { doc.setTextColor(50,50,50); addLine(`• ${d}`, 8); });
      yRef.y += 8;
    }
    if (data?.action_items?.length) {
      addPdfSection(doc, "✅", "Action Items", yRef, pageH, margin, lineH, addLine);
      data.action_items.forEach((a, i) => {
        doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(50,50,50);
        addLine(`Action ${i + 1}: ${a.task}`, 8);
        doc.setFont("helvetica", "normal"); doc.setTextColor(100,100,100);
        addLine(`Owner: ${a.owner || "Unassigned"}  |  Deadline: ${a.deadline || "TBD"}  |  Priority: ${a.priority}`, 16);
        yRef.y += 4;
      });
      yRef.y += 4;
    }
    if (data?.next_steps?.length) {
      addPdfSection(doc, "🔜", "Next Steps", yRef, pageH, margin, lineH, addLine);
      data.next_steps.forEach(s => { doc.setTextColor(50,50,50); addLine(`• ${s}`, 8); });
      yRef.y += 8;
    }
    if (data?.risks?.length) {
      addPdfSection(doc, "⚠️", "Risks & Gaps", yRef, pageH, margin, lineH, addLine);
      data.risks.forEach(r => { doc.setTextColor(50,50,50); addLine(`• ${r}`, 8); });
      yRef.y += 8;
    }
    if (data?.ai_insights?.length) {
      addPdfSection(doc, "💡", "AI Insights", yRef, pageH, margin, lineH, addLine);
      data.ai_insights.forEach(ins => { doc.setTextColor(50,50,50); addLine(`• ${ins}`, 8); });
    }

    // Footer
    yRef.y += 16;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    addLine("Generated by SILO");

    doc.save(`${session.title || "minutes"}.pdf`);
    setLoading(null);
  };

  const handleEmailTeam = () => {
    const subject = encodeURIComponent(session.title || "Meeting Minutes");
    const body = encodeURIComponent(plainText);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const handleShare = async () => {
    try {
      if (navigator.share) {
        await navigator.share({ title: session.title || "Session Minutes", text: plainText });
      } else {
        await navigator.clipboard.writeText(plainText);
      alert("Copied to clipboard!");
      }
    } catch (error) {
      if (error.name !== "AbortError") {
        await navigator.clipboard.writeText(plainText);
        alert("Copied to clipboard!");
      }
    }
  };

  return (
    <div className="flex items-center gap-1">
      <Button
        variant="ghost"
        size="sm"
        onClick={handleShare}
        className="gap-1.5 text-xs"
        title="Share"
      >
        <Share2 className="w-3.5 h-3.5" />
      </Button>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" size="sm" className="px-1.5" title="Export options">
            <MoreHorizontal className="w-4 h-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={handleDownloadText}>
            <FileText className="w-3.5 h-3.5 mr-2" /> Download TXT
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleEmailTeam}>
            <Mail className="w-3.5 h-3.5 mr-2" /> Email to Team
            <span className="ml-auto text-[9px] px-1.5 py-0.5 rounded-full font-semibold bg-purple-500/20 text-purple-400">Beta</span>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}