import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  X, FileText, Loader2, Download, ChevronDown, ChevronUp,
  Folder, RefreshCw, Clock, FileDown, AlignLeft, BookOpen,
} from "lucide-react";
import { appClient } from "@/api/appClient";
import { useTheme } from "@/lib/ThemeContext";
import { generateSiloDocx } from "@/lib/siloDocxExport";
import jsPDF from "jspdf";

function formatDuration(secs) {
  if (!secs) return "";
  const m = Math.floor(secs / 60);
  const h = Math.floor(m / 60);
  if (h > 0) return `${h}h ${m % 60}m`;
  return `${m}m`;
}

// ─── PDF Generator (matching DOCX layout) ─────────────────────────────────
function generatePDF({ report, folderName, sessions, generatedAt }) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, H = 297;
  const ML = 20, MR = 20, MT = 25;
  let y = MT;
  const maxW = W - ML - MR;

  const gold = [184, 134, 11];
  const navy = [27, 42, 74];
  const darkGray = [100, 100, 100];
  const black = [30, 30, 30];
  const lightGray = [245, 245, 245];
  const white = [255, 255, 255];

  function setColor(r, g, b) { doc.setTextColor(r, g, b); }
  function setFill(r, g, b) { doc.setFillColor(r, g, b); }
  function setDraw(r, g, b) { doc.setDrawColor(r, g, b); }

  function addPage() {
    doc.addPage();
    y = MT;
    // Header line
    setDraw(...gold);
    doc.setLineWidth(0.5);
    doc.line(ML, 12, W - MR, 12);
    doc.setFontSize(8);
    setColor(...darkGray);
    doc.text(`Silo AI — Session Minutes  |  ${folderName}`, W - MR, 10, { align: "right" });
    // Footer
    doc.line(ML, H - 10, W - MR, H - 10);
    doc.text(`CONFIDENTIAL — Generated by Silo AI  |  Page ${doc.internal.getNumberOfPages()}`, W / 2, H - 6, { align: "center" });
  }

  function checkPage(needed = 10) {
    if (y + needed > H - 18) addPage();
  }

  function heading1(text) {
    checkPage(18);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    setColor(...navy);
    doc.text(text, ML, y);
    y += 4;
    setDraw(...gold);
    doc.setLineWidth(0.6);
    doc.line(ML, y, W - MR, y);
    y += 8;
  }

  function heading2(text) {
    checkPage(12);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    setColor(...navy);
    doc.text(text, ML, y);
    y += 7;
  }

  function heading3(text) {
    checkPage(10);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    setColor(44, 82, 130);
    doc.text(text, ML, y);
    y += 6;
  }

  function body(text, indent = 0) {
    if (!text) return;
    checkPage(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    setColor(...black);
    const lines = doc.splitTextToSize(text, maxW - indent);
    lines.forEach(line => {
      checkPage(6);
      doc.text(line, ML + indent, y);
      y += 5.5;
    });
  }

  function bullet(text) {
    if (!text) return;
    checkPage(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    setColor(...black);
    const lines = doc.splitTextToSize(text, maxW - 6);
    doc.text("•", ML + 2, y);
    lines.forEach((line, i) => {
      checkPage(6);
      doc.text(line, ML + 7, y);
      y += 5.5;
    });
  }

  function space(n = 4) { y += n; }

  function tableRow(cols, widths, isHeader = false) {
    checkPage(10);
    const rowH = 8;
    let x = ML;
    if (isHeader) {
      setFill(...navy);
      doc.rect(ML, y - 5, maxW, rowH, "F");
    } else if (cols._alt) {
      setFill(...lightGray);
      doc.rect(ML, y - 5, maxW, rowH, "F");
    }
    cols.forEach((col, i) => {
      const w = widths[i];
      doc.setFontSize(9);
      doc.setFont("helvetica", isHeader ? "bold" : "normal");
      setColor(...(isHeader ? white : black));
      const text = String(col || "");
      const lines = doc.splitTextToSize(text, w - 3);
      doc.text(lines[0] || "", x + 2, y);
      setDraw(...[200, 200, 200]);
      doc.setLineWidth(0.2);
      doc.rect(x, y - 5, w, rowH);
      x += w;
    });
    y += rowH - 1;
  }

  function dividerLine() {
    space(2);
    setDraw(...gold);
    doc.setLineWidth(0.4);
    doc.line(ML, y, W - MR, y);
    space(4);
  }

  // ── COVER PAGE ──────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  setColor(...darkGray);
  doc.text("SILO AI — MEETING INTELLIGENCE", W / 2, y, { align: "center" });
  y += 12;

  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  setColor(...navy);
  doc.text("SESSION MINUTES", W / 2, y, { align: "center" });
  y += 12;

  doc.setFontSize(18);
  setColor(...gold);
  doc.text(folderName, W / 2, y, { align: "center" });
  y += 8;

  if (report.overall_objective) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "italic");
    setColor(...darkGray);
    const objLines = doc.splitTextToSize(report.overall_objective, maxW);
    objLines.forEach(l => { doc.text(l, W / 2, y, { align: "center" }); y += 6; });
  }
  y += 4;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  setColor(...darkGray);
  const dateStr = generatedAt ? new Date(generatedAt).toLocaleDateString("en-GB", { weekday: "long", year: "numeric", month: "long", day: "numeric" }) : new Date().toLocaleDateString("en-GB", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  doc.text(dateStr, W / 2, y, { align: "center" });
  y += 14;

  setDraw(...gold);
  doc.setLineWidth(1);
  doc.line(ML + 20, y, W - MR - 20, y);
  y += 12;

  // ── 1. MEETING DETAILS ──────────────────────────────────────────
  heading1("1.  Meeting Details");
  const sessionTitles = (sessions || []).map(s => s.title || "Untitled").join("; ");
  const detailRows = [
    ["SESSION TITLE", folderName],
    ["DATE", dateStr],
    ["SESSIONS COVERED", `${(sessions || []).length} session(s): ${sessionTitles}`],
    ["PREPARED BY", "Silo AI"],
    ["STATUS", "AI GENERATED — FOR REVIEW"],
    ["CLASSIFICATION", "CONFIDENTIAL"],
  ];
  const dw = [50, maxW - 50];
  detailRows.forEach((row, i) => {
    if (i % 2 === 0) row._alt = true;
    tableRow(row, dw, false);
  });
  space(6);

  // ── 2. EXECUTIVE SUMMARY ────────────────────────────────────────
  heading1("2.  Executive Summary");
  body(report.executive_summary);
  if (report.overall_objective) { space(3); body(`Objective: ${report.overall_objective}`, 0); }
  space(6);

  // ── 3. AGENDA ───────────────────────────────────────────────────
  heading1("3.  Session Agenda");
  const agW = [(maxW - 10) * 0.1, (maxW - 10) * 0.55, (maxW - 10) * 0.25, (maxW - 10) * 0.1];
  tableRow(["#", "Session Title", "Date", "Duration"], agW, true);
  (sessions || []).forEach((s, i) => {
    tableRow([String(i + 1), s.title || `Session ${i + 1}`, s.created_date ? new Date(s.created_date).toLocaleDateString() : "", s.duration ? `${Math.round(s.duration / 60)}m` : ""], agW);
  });
  space(6);

  // ── 4. KEY DISCUSSIONS ──────────────────────────────────────────
  heading1("4.  Key Discussions");
  (report.discussion_topics || []).forEach((t, i) => {
    heading3(`Discussion ${i + 1}: ${t.topic}`);
    body(t.description);
    if (t.key_points?.length) t.key_points.forEach(kp => bullet(kp));
    if (t.speakers_involved?.length) body(`Participants: ${t.speakers_involved.join(", ")}`, 0);
    space(4);
  });

  // ── 5. DECISIONS ────────────────────────────────────────────────
  if ((report.decisions || []).length > 0) {
    dividerLine();
    heading1("5.  Decisions & Agreements");
    const dW = [(maxW) * 0.08, (maxW) * 0.77, (maxW) * 0.15];
    tableRow(["#", "Decision / Agreement", "Status"], dW, true);
    (report.decisions || []).forEach((d, i) => tableRow([String(i + 1), d, "Agreed"], dW));
    space(6);
  }

  // ── 6. ACTION ITEMS ─────────────────────────────────────────────
  if ((report.action_items || []).length > 0) {
    dividerLine();
    heading1("6.  Action Items");
    const aW = [(maxW) * 0.07, (maxW) * 0.56, (maxW) * 0.24, (maxW) * 0.13];
    tableRow(["#", "Action Item", "Owner", "Due"], aW, true);
    (report.action_items || []).forEach((a, i) => tableRow([String(i + 1), a.task || "", a.owner || "TBD", a.due || "TBD"], aW));
    space(6);
  }

  // ── 7. KEY OUTCOMES ─────────────────────────────────────────────
  if ((report.key_outcomes || []).length > 0) {
    dividerLine();
    heading1("7.  Key Outcomes");
    (report.key_outcomes || []).forEach(o => bullet(o));
    space(6);
  }

  // ── 8. FULL MINUTES ─────────────────────────────────────────────
  if ((report.minutes || []).length > 0) {
    dividerLine();
    heading1("8.  Full Meeting Minutes");
    (report.minutes || []).forEach((m, i) => {
      heading2(m.session_label || `Session ${i + 1}`);
      (m.highlights || []).forEach(h => bullet(h));
      space(4);
    });
  }

  // ── CLOSING ─────────────────────────────────────────────────────
  dividerLine();
  body(report.closing_remarks || "This report was automatically generated by Silo AI based on the recorded session transcripts.");
  space(8);
  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  setColor(...darkGray);
  doc.text("— End of Report —", W / 2, y, { align: "center" });

  // Footer on last page
  doc.line(ML, H - 10, W - MR, H - 10);
  doc.setFontSize(8);
  setColor(...darkGray);
  doc.text(`CONFIDENTIAL — Generated by Silo AI  |  Page ${doc.internal.getNumberOfPages()}`, W / 2, H - 6, { align: "center" });

  return doc;
}

// ─── Main Modal ────────────────────────────────────────────────────────────
export default function FolderReportModal({ folderName, sessions, user, onClose, initialReport }) {
  const { isDark } = useTheme();
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState(null);
  const [report, setReport] = useState(initialReport?.report_data || null);
  const [savedReport, setSavedReport] = useState(initialReport || null);
  const [expandedSection, setExpandedSection] = useState(null);
  const [exportMenuOpen, setExportMenuOpen] = useState(false);
  const [loadingExport, setLoadingExport] = useState(null);

  const text = isDark ? "text-white" : "text-gray-900";
  const sub = isDark ? "text-white/50" : "text-gray-500";
  const card = isDark ? "bg-[#1C1C1E] border-white/8" : "bg-white border-gray-200";

  const folderSessions = sessions.filter(s => s.folder === folderName);

  // Load saved report on open (only if not pre-loaded)
  useEffect(() => {
    if (initialReport) { setExpandedSection("executive"); return; }
    const load = async () => {
      if (!user?.email) return;
      const existing = await appClient.entities.FolderReport.filter({ user_email: user.email, folder_name: folderName }, "-created_date", 1);
      if (existing.length > 0) {
        setSavedReport(existing[0]);
        setReport(existing[0].report_data);
        setExpandedSection("executive");
      }
    };
    load();
  }, [folderName, user, initialReport]);

  // ── Hierarchical summarization helpers ──────────────────────────────────
  const CHUNK_SIZE = 8000; // chars per chunk (~1200-1600 words)

  const chunkText = (text) => {
    const chunks = [];
    for (let i = 0; i < text.length; i += CHUNK_SIZE) {
      chunks.push(text.slice(i, i + CHUNK_SIZE));
    }
    return chunks;
  };

  const summarizeChunk = async (chunk, sessionTitle, chunkIndex, totalChunks) => {
    const result = await appClient.integrations.Core.InvokeLLM({
      prompt: `You are extracting detailed notes from part ${chunkIndex + 1} of ${totalChunks} of a meeting/session transcript titled "${sessionTitle}".

Extract EVERYTHING of value — do not summarise too aggressively. Preserve:
- Every topic and sub-topic discussed (with context)
- All decisions made, even tentative ones
- Every action item and commitment (who, what, when)
- All speaker names and what each person said
- Specific facts, numbers, dates, percentages, names of tools/projects/companies
- Any questions raised and answers given
- Disagreements, tensions, or open issues
- Direct quotes where they add value

Write in structured bullet points grouped by topic. Be comprehensive — this will be used to write detailed official meeting minutes.

TRANSCRIPT CHUNK:
${chunk}`,
    });
    return result;
  };

  const getSessionContent = async (session, index) => {
    const rawText = session.transcript_text || session.summary_text || "";
    const meta = [
      `--- Session ${index + 1}: ${session.title || "Untitled"} ---`,
      session.created_date ? `Date: ${new Date(session.created_date).toLocaleString()}` : "",
      session.duration ? `Duration: ${formatDuration(session.duration)}` : "",
      session.session_type ? `Type: ${session.session_type}` : "",
      session.calendar_event_title ? `Event: ${session.calendar_event_title}` : "",
      session.calendar_attendees?.length ? `Attendees: ${session.calendar_attendees.join(", ")}` : "",
    ].filter(Boolean).join("\n");

    if (!rawText) return meta;

    // If short enough, use directly
    if (rawText.length <= CHUNK_SIZE) {
      return `${meta}\nContent:\n${rawText}`;
    }

    // Hierarchical: chunk → summarize each chunk → combine summaries
    const chunks = chunkText(rawText);
    const chunkSummaries = await Promise.all(
      chunks.map((chunk, i) => summarizeChunk(chunk, session.title || `Session ${index + 1}`, i, chunks.length))
    );

    const combinedSummary = chunkSummaries.join("\n\n---\n\n");

    // If combined summaries are still too large, do a second pass
    if (combinedSummary.length > CHUNK_SIZE * 2) {
      const secondPass = await appClient.integrations.Core.InvokeLLM({
        prompt: `You are consolidating multiple chunk summaries of a session titled "${session.title || "Untitled"}".
Merge these summaries into ONE comprehensive summary preserving ALL key points, decisions, action items, and facts.

SUMMARIES:
${combinedSummary}`,
      });
      return `${meta}\nContent:\n${secondPass}`;
    }

    return `${meta}\nContent:\n${combinedSummary}`;
  };

  const generateReport = async () => {
    setGenerating(true);
    setGenerateError(null);
    setReport(null);

    try {
    // Process each session with hierarchical summarization (full transcript, no truncation)
    const sessionContents = await Promise.all(
      folderSessions.map((s, i) => getSessionContent(s, i))
    );
    const sessionDocs = sessionContents.join("\n\n");

    const result = await appClient.integrations.Core.InvokeLLM({
      model: "gpt_5",
      prompt: `You are a senior meeting analyst and professional minutes writer tasked with producing HIGHLY DETAILED, OFFICIAL MEETING MINUTES for the folder/project "${folderName}".

You have ${folderSessions.length} session(s) below. This is a formal record — be exhaustive, specific, and structured. Use real names, exact topics, verbatim quotes where possible, and specific figures/numbers from the content. Do NOT generalise — every detail matters.

${sessionDocs}

DETAILED INSTRUCTIONS FOR EACH FIELD:

- executive_summary: Write a rich 8–12 sentence executive summary. Cover: the overall context and purpose, who was involved, the main themes and topics discussed, key tensions or debates, what was resolved, what remains open, and the significance of this session for the project/team.

- overall_objective: One precise sentence describing the primary goal of this set of sessions.

- session_format: Describe the format in detail (e.g. "Multi-session strategic workshop with Q&A and breakout discussions").

- discussion_topics: Extract EVERY significant topic discussed. For each topic:
  * topic: Clear title
  * description: 4–6 detailed sentences explaining what was discussed, the context, different viewpoints expressed, and how the conversation evolved.
  * key_points: 5–10 specific bullet points capturing exactly what was said — include facts, figures, names, and direct references.
  * speakers_involved: List all identifiable speakers/participants.

- decisions: List EVERY decision, agreement, or resolution reached. Be specific — include what was decided, by whom, and any conditions or caveats. Minimum 1 sentence per decision.

- action_items: Every task, follow-up, or commitment mentioned. For each: exact task description, who is responsible, and deadline if mentioned.

- key_outcomes: Concrete, tangible results and outputs from the sessions. Be specific — reference actual deliverables, agreements, or changes in direction.

- minutes: Produce DETAILED per-session minutes. For each session, write 8–15 comprehensive bullet highlights that capture the full narrative of what happened — not just topics, but the flow and substance of discussion.

- closing_remarks: A professional 3–4 sentence closing paragraph summarising what was accomplished, what the next steps are, and what the team should focus on going forward.

- agenda: If the content mentions a structured agenda, capture it fully.`,
      response_json_schema: {
        type: "object",
        properties: {
          executive_summary: { type: "string" },
          overall_objective: { type: "string" },
          session_format: { type: "string" },
          discussion_topics: {
            type: "array",
            items: {
              type: "object",
              properties: {
                topic: { type: "string" },
                description: { type: "string" },
                key_points: { type: "array", items: { type: "string" } },
                speakers_involved: { type: "array", items: { type: "string" } },
              }
            }
          },
          decisions: { type: "array", items: { type: "string" } },
          action_items: {
            type: "array",
            items: {
              type: "object",
              properties: {
                task: { type: "string" },
                owner: { type: "string" },
                due: { type: "string" },
              }
            }
          },
          key_outcomes: { type: "array", items: { type: "string" } },
          minutes: {
            type: "array",
            items: {
              type: "object",
              properties: {
                session_label: { type: "string" },
                highlights: { type: "array", items: { type: "string" } },
              }
            }
          },
          closing_remarks: { type: "string" },
          agenda: {
            type: "array",
            items: {
              type: "object",
              properties: {
                session: { type: "string" },
                time: { type: "string" },
                topic: { type: "string" },
                duration: { type: "string" },
              }
            }
          },
        }
      }
    });

    // Save / update in DB
    const reportRecord = {
      user_email: user.email,
      folder_name: folderName,
      session_ids: folderSessions.map(s => s.id),
      session_count: folderSessions.length,
      report_data: result,
      generated_at: new Date().toISOString(),
      title: `${folderName} — Report`,
    };

    let saved;
    if (savedReport?.id) {
      saved = await appClient.entities.FolderReport.update(savedReport.id, reportRecord);
    } else {
      saved = await appClient.entities.FolderReport.create(reportRecord);
    }

    setSavedReport(saved);
    setReport(result);
    setExpandedSection("executive");
    } catch (err) {
      console.error("Folder report generation failed:", err);
      setGenerateError(err?.message || "Failed to generate report. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  // ── Export handlers ──────────────────────────────────────────────────────
  const exportTxt = () => {
    if (!report) return;
    const lines = [
      `SILO AI — SESSION MINUTES`,
      `FOLDER: ${folderName}`,
      `Generated: ${new Date().toLocaleString()}`,
      `Sessions: ${folderSessions.length}`,
      "",
      "═══════════════════════════════════════",
      "EXECUTIVE SUMMARY",
      "═══════════════════════════════════════",
      report.executive_summary || "",
      "",
      `Objective: ${report.overall_objective || ""}`,
      "",
      "═══════════════════════════════════════",
      "KEY DISCUSSION TOPICS",
      "═══════════════════════════════════════",
      ...(report.discussion_topics || []).flatMap((t, i) => [
        ``,
        `${i + 1}. ${t.topic}`,
        t.description || "",
        ...(t.key_points || []).map(kp => `   • ${kp}`),
        ...(t.speakers_involved?.length ? [`   Participants: ${t.speakers_involved.join(", ")}`] : []),
      ]),
      "",
      "═══════════════════════════════════════",
      "DECISIONS & AGREEMENTS",
      "═══════════════════════════════════════",
      ...(report.decisions || []).map((d, i) => `${i + 1}. ${d}`),
      "",
      "═══════════════════════════════════════",
      "ACTION ITEMS",
      "═══════════════════════════════════════",
      ...(report.action_items || []).map((a, i) => `${i + 1}. ${a.task}${a.owner ? ` — ${a.owner}` : ""}${a.due ? ` (${a.due})` : ""}`),
      "",
      "═══════════════════════════════════════",
      "KEY OUTCOMES",
      "═══════════════════════════════════════",
      ...(report.key_outcomes || []).map(o => `• ${o}`),
      "",
      "═══════════════════════════════════════",
      "FULL MEETING MINUTES",
      "═══════════════════════════════════════",
      ...(report.minutes || []).flatMap(m => [
        ``,
        m.session_label || "",
        ...(m.highlights || []).map(h => `  • ${h}`),
      ]),
      "",
      "═══════════════════════════════════════",
      report.closing_remarks || "",
      `— End of Report — Generated by Silo AI`,
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${folderName.replace(/\s+/g, "_")}_Minutes.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportDocx = async () => {
    setLoadingExport("docx");
    const blob = await generateSiloDocx({
      report,
      folderName,
      sessions: folderSessions,
      generatedAt: savedReport?.generated_at,
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${folderName.replace(/\s+/g, "_")}_Minutes.docx`;
    a.click();
    URL.revokeObjectURL(url);
    setLoadingExport(null);
    setExportMenuOpen(false);
  };

  const exportPdf = () => {
    setLoadingExport("pdf");
    const pdf = generatePDF({
      report,
      folderName,
      sessions: folderSessions,
      generatedAt: savedReport?.generated_at,
    });
    pdf.save(`${folderName.replace(/\s+/g, "_")}_Minutes.pdf`);
    setLoadingExport(null);
    setExportMenuOpen(false);
  };

  // ── Section accordion ───────────────────────────────────────────────────
  const Section = ({ id, title, icon, children }) => {
    const open = expandedSection === id;
    return (
      <div className={`rounded-xl border overflow-hidden ${card}`}>
        <button
          onClick={() => setExpandedSection(open ? null : id)}
          className={`w-full flex items-center justify-between px-4 py-3 ${isDark ? "hover:bg-white/4" : "hover:bg-gray-50"} transition-colors`}
        >
          <div className="flex items-center gap-2.5">
            <span className="text-base">{icon}</span>
            <span className={`text-sm font-semibold ${text}`}>{title}</span>
          </div>
          {open ? <ChevronUp className={`w-4 h-4 ${sub}`} /> : <ChevronDown className={`w-4 h-4 ${sub}`} />}
        </button>
        {open && <div className={`px-4 pb-4 border-t ${isDark ? "border-white/6" : "border-gray-100"}`}>{children}</div>}
      </div>
    );
  };

  return (
    <div className="fixed inset-0 z-50 flex flex-col" style={{ background: "rgba(0,0,0,0.75)", backdropFilter: "blur(6px)" }}>
      <motion.div
        initial={{ y: "100%" }}
        animate={{ y: 0 }}
        exit={{ y: "100%" }}
        transition={{ type: "spring", damping: 28, stiffness: 300 }}
        className={`absolute inset-x-0 bottom-0 top-10 rounded-t-2xl flex flex-col overflow-hidden ${isDark ? "bg-[#111111]" : "bg-[#F5F5F7]"}`}
      >
        {/* Header */}
        <div className={`flex items-center justify-between px-5 py-4 border-b ${isDark ? "border-white/8" : "border-gray-200"} shrink-0`}>
          <div className="flex items-center gap-2.5">
            <Folder className="w-5 h-5 text-purple-400" />
            <div>
              <p className={`text-[10px] uppercase tracking-widest ${sub}`}>Folder Report</p>
              <h2 className={`text-base font-bold ${text}`}>{folderName}</h2>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {savedReport && (
              <div className={`flex items-center gap-1 text-[10px] ${sub}`}>
                <Clock className="w-3 h-3" />
                <span>{new Date(savedReport.generated_at || savedReport.created_date).toLocaleDateString()}</span>
              </div>
            )}
            {report && (
              <div className="relative">
                <button
                  onClick={() => setExportMenuOpen(v => !v)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-purple-500/20 text-purple-400 hover:bg-purple-500/30 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Export
                  <ChevronDown className="w-3 h-3" />
                </button>
                {exportMenuOpen && (
                  <>
                    <div className="fixed inset-0 z-10" onClick={() => setExportMenuOpen(false)} />
                    <div className={`absolute right-0 top-full mt-1.5 w-44 rounded-xl border shadow-xl z-20 overflow-hidden ${isDark ? "bg-[#1C1C1E] border-white/10" : "bg-white border-gray-200"}`}>
                      <button onClick={() => { exportTxt(); setExportMenuOpen(false); }} className={`w-full flex items-center gap-2.5 px-4 py-2.5 text-left text-sm ${isDark ? "text-white/70 hover:bg-white/6" : "text-gray-700 hover:bg-gray-50"}`}>
                        <AlignLeft className="w-4 h-4 text-gray-400" /> Plain Text
                      </button>
                      <button onClick={exportDocx} disabled={loadingExport === "docx"} className={`w-full flex items-center gap-2.5 px-4 py-2.5 text-left text-sm ${isDark ? "text-white/70 hover:bg-white/6" : "text-gray-700 hover:bg-gray-50"}`}>
                        {loadingExport === "docx" ? <Loader2 className="w-4 h-4 animate-spin text-blue-400" /> : <FileDown className="w-4 h-4 text-blue-400" />}
                        Word (.docx)
                      </button>
                      <button onClick={exportPdf} disabled={loadingExport === "pdf"} className={`w-full flex items-center gap-2.5 px-4 py-2.5 text-left text-sm ${isDark ? "text-white/70 hover:bg-white/6" : "text-gray-700 hover:bg-gray-50"}`}>
                        {loadingExport === "pdf" ? <Loader2 className="w-4 h-4 animate-spin text-red-400" /> : <BookOpen className="w-4 h-4 text-red-400" />}
                        PDF
                      </button>
                    </div>
                  </>
                )}
              </div>
            )}
            <button onClick={onClose} className={`w-8 h-8 rounded-full flex items-center justify-center ${isDark ? "bg-white/8 text-white/50 hover:bg-white/14" : "bg-gray-100 text-gray-500 hover:bg-gray-200"}`}>
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Session pills */}
        <div className="px-5 py-2.5 flex gap-2 overflow-x-auto scrollbar-hide shrink-0">
          {folderSessions.map((s, i) => (
            <span key={s.id} className={`shrink-0 text-[10px] px-2.5 py-1 rounded-full border ${isDark ? "bg-white/5 border-white/10 text-white/50" : "bg-white border-gray-200 text-gray-500"}`}>
              {s.title || `Session ${i + 1}`}
            </span>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto px-5 pb-8">
          {/* Empty / Generate state */}
          {generateError && !generating && !report && (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <div className={`w-14 h-14 rounded-full flex items-center justify-center mb-4 ${isDark ? "bg-red-500/15" : "bg-red-50"}`}>
                <X className="w-6 h-6 text-red-400" />
              </div>
              <h3 className={`text-base font-semibold mb-2 ${text}`}>Report generation failed</h3>
              <p className={`text-sm mb-5 max-w-sm ${sub}`}>{generateError}</p>
              <button
                onClick={generateReport}
                className="flex items-center gap-2 px-5 py-2.5 rounded-full text-sm font-semibold text-white"
                style={{ background: "linear-gradient(135deg,#A855F7,#6366F1)" }}
              >
                <FileText className="w-4 h-4" />
                Try Again
              </button>
            </div>
          )}

          {!report && !generating && !generateError && (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <div className="w-16 h-16 rounded-full flex items-center justify-center mb-5" style={{ background: "linear-gradient(135deg,#A855F7,#6366F1)" }}>
                <FileText className="w-7 h-7 text-white" />
              </div>
              <h3 className={`text-lg font-bold mb-2 ${text}`}>Generate Folder Report</h3>
              <p className={`text-sm mb-6 max-w-xs ${sub}`}>
                Consolidate {folderSessions.length} session{folderSessions.length !== 1 ? "s" : ""} into one comprehensive, professional report with full meeting minutes.
              </p>
              <button
                onClick={generateReport}
                className="flex items-center gap-2.5 px-6 py-3 rounded-full text-sm font-semibold text-white"
                style={{ background: "linear-gradient(135deg,#A855F7,#6366F1)", boxShadow: "0 8px 24px rgba(139,92,246,0.35)" }}
              >
                <FileText className="w-4 h-4" />
                Generate Report
              </button>
            </div>
          )}

          {/* Generating */}
          {generating && (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <Loader2 className="w-8 h-8 animate-spin text-purple-400 mb-4" />
              <p className={`text-sm font-medium ${text}`}>Analysing {folderSessions.length} session{folderSessions.length !== 1 ? "s" : ""}…</p>
              <p className={`text-xs mt-1.5 ${sub}`}>Processing full transcripts — this may take a minute</p>
              <p className={`text-[10px] mt-1 ${sub} opacity-70`}>Long sessions are summarised in chunks for full coverage</p>
            </div>
          )}

          {/* Report */}
          {report && !generating && (
            <div className="space-y-3 mt-2">

              {/* Executive Summary */}
              <Section id="executive" title="Executive Summary" icon="📋">
                <div className="pt-3 space-y-3">
                  {report.overall_objective && (
                    <div className={`rounded-lg p-3 ${isDark ? "bg-purple-500/10 border border-purple-500/20" : "bg-purple-50 border border-purple-100"}`}>
                      <p className="text-[10px] uppercase font-semibold text-purple-400 mb-1">Objective</p>
                      <p className={`text-sm ${text}`}>{report.overall_objective}</p>
                    </div>
                  )}
                  <p className={`text-sm leading-relaxed ${text}`}>{report.executive_summary}</p>
                </div>
              </Section>

              {/* Discussion Topics */}
              {(report.discussion_topics || []).length > 0 && (
                <Section id="topics" title="Key Discussion Topics" icon="💬">
                  <div className="pt-3 space-y-4">
                    {report.discussion_topics.map((t, i) => (
                      <div key={i} className={`rounded-lg p-3 border ${isDark ? "bg-white/3 border-white/8" : "bg-gray-50 border-gray-100"}`}>
                        <p className={`text-sm font-semibold mb-2 ${text}`}>{i + 1}. {t.topic}</p>
                        <p className={`text-xs leading-relaxed mb-2 ${sub}`}>{t.description}</p>
                        {(t.key_points || []).length > 0 && (
                          <div className="space-y-1 mt-2">
                            {t.key_points.map((kp, j) => (
                              <div key={j} className="flex gap-2">
                                <span className="text-purple-400 text-xs shrink-0">▸</span>
                                <p className={`text-xs leading-relaxed ${text}`}>{kp}</p>
                              </div>
                            ))}
                          </div>
                        )}
                        {(t.speakers_involved || []).length > 0 && (
                          <p className={`text-[10px] mt-2 italic ${sub}`}>Participants: {t.speakers_involved.join(", ")}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Decisions */}
              {(report.decisions || []).length > 0 && (
                <Section id="decisions" title="Decisions & Agreements" icon="✅">
                  <div className="pt-3 space-y-2">
                    {report.decisions.map((d, i) => (
                      <div key={i} className="flex gap-2.5">
                        <span className={`text-xs font-semibold shrink-0 w-5 h-5 rounded-full flex items-center justify-center ${isDark ? "bg-green-500/20 text-green-400" : "bg-green-100 text-green-700"}`}>{i + 1}</span>
                        <p className={`text-sm leading-relaxed ${text}`}>{d}</p>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Action Items */}
              {(report.action_items || []).length > 0 && (
                <Section id="actions" title="Action Items" icon="⚡">
                  <div className="pt-3 space-y-2.5">
                    {report.action_items.map((a, i) => (
                      <div key={i} className={`rounded-lg p-3 border ${isDark ? "bg-blue-500/8 border-blue-500/20" : "bg-blue-50 border-blue-100"}`}>
                        <p className={`text-sm font-medium ${text}`}>{a.task}</p>
                        <div className="flex gap-3 mt-1.5 flex-wrap">
                          {a.owner && <span className={`text-[10px] px-2 py-0.5 rounded-full ${isDark ? "bg-blue-500/15 text-blue-400" : "bg-blue-100 text-blue-700"}`}>👤 {a.owner}</span>}
                          {a.due && <span className={`text-[10px] px-2 py-0.5 rounded-full ${isDark ? "bg-amber-500/15 text-amber-400" : "bg-amber-100 text-amber-700"}`}>📅 {a.due}</span>}
                        </div>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Key Outcomes */}
              {(report.key_outcomes || []).length > 0 && (
                <Section id="outcomes" title="Key Outcomes" icon="🎯">
                  <div className="pt-3 space-y-2">
                    {report.key_outcomes.map((o, i) => (
                      <div key={i} className="flex gap-2.5">
                        <span className="text-amber-400 text-sm shrink-0 mt-0.5">▸</span>
                        <p className={`text-sm leading-relaxed ${text}`}>{o}</p>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Full Minutes */}
              {(report.minutes || []).length > 0 && (
                <Section id="minutes" title="Full Meeting Minutes" icon="📝">
                  <div className="pt-3 space-y-5">
                    {report.minutes.map((m, i) => (
                      <div key={i}>
                        <div className={`flex items-center gap-2 mb-2 pb-1.5 border-b ${isDark ? "border-white/8" : "border-gray-100"}`}>
                          <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${isDark ? "bg-purple-500/15 text-purple-400" : "bg-purple-100 text-purple-700"}`}>Session {i + 1}</span>
                          <p className={`text-xs font-semibold ${text}`}>{m.session_label}</p>
                        </div>
                        <div className="space-y-1.5 pl-2">
                          {(m.highlights || []).map((h, j) => (
                            <div key={j} className="flex gap-2">
                              <span className={`text-xs shrink-0 mt-0.5 ${sub}`}>•</span>
                              <p className={`text-sm leading-relaxed ${text}`}>{h}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Closing */}
              {report.closing_remarks && (
                <Section id="closing" title="Closing Remarks" icon="🔚">
                  <p className={`pt-3 text-sm leading-relaxed ${text}`}>{report.closing_remarks}</p>
                </Section>
              )}

              {/* Regenerate */}
              <button
                onClick={generateReport}
                disabled={generating}
                className={`w-full py-3 rounded-xl text-sm font-medium border flex items-center justify-center gap-2 transition-colors ${isDark ? "border-white/8 text-white/40 hover:bg-white/5 hover:text-white/60" : "border-gray-200 text-gray-400 hover:bg-gray-50"}`}
              >
                <RefreshCw className="w-4 h-4" />
                Regenerate Report
              </button>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}