import React, { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Sparkles, RefreshCw, Loader2, Mic } from "lucide-react";
import { appClient } from "@/api/appClient";
import StructuredMinutes from "./StructuredMinutes";
import ExportShare from "./ExportShare";
import TranscriptQualityWarning from "./TranscriptQualityWarning";
import RegenerationWarningDialog from "./RegenerationWarningDialog";

const TRUNCATED_MARKERS = ["...[truncated", "see transcript_file_url", "[upload failed; transcript truncated]"];

async function resolveSubsessionTranscript(sub) {
  const inline = (sub?.transcript_text || "").trim();
  const fileUrl = sub?.transcript_file_url;
  if (fileUrl && (!inline || TRUNCATED_MARKERS.some(m => inline.includes(m)))) {
    try {
      const res = await fetch(fileUrl);
      if (res.ok) { const full = (await res.text())?.trim(); if (full) return full; }
    } catch {}
  }
  return inline;
}

async function buildMergedTranscript(subsessions) {
  if (!subsessions || subsessions.length === 0) return null;
  const sorted = [...subsessions].sort((a, b) => new Date(a.created_date) - new Date(b.created_date));
  const parts = await Promise.all(sorted.map(async (sub, idx) => {
    const body = await resolveSubsessionTranscript(sub);
    return body ? `[Part ${idx + 1}]\n${body}` : `[Part ${idx + 1}]`;
  }));
  return parts.join("\n");
}

export default function SummarySection({ session, sessionId, summary, transcript, subsessions, audioUrl, onSummaryGenerated, onTranscriptGenerated, manualNotes }) {
  const [loading, setLoading] = useState(false);
  const [transcribing, setTranscribing] = useState(false);
  const [qualityIssue, setQualityIssue] = useState(null);
  const [retrying, setRetrying] = useState(false);
  const [originalSummary, setOriginalSummary] = useState(session?.original_summary_text || null);
  const [showRegenerationWarning, setShowRegenerationWarning] = useState(false);

  const transcribeAudio = async () => {
    if (!audioUrl) return;
    setTranscribing(true);
    try {
      const response = await appClient.functions.invoke('transcribeAudio', { audio_url: audioUrl, session_id: sessionId });
      const data = response.data;
      if (data?.status === 'processing') {
        // AssemblyAI job submitted asynchronously — UI will update via polling in SessionDetail
        setTranscribing(false);
        return;
      }
      const text = data?.transcript;
      if (!text) throw new Error("No transcript returned");
      await appClient.entities.Session.update(sessionId, { transcript_text: text });
      if (onTranscriptGenerated) onTranscriptGenerated(text);
      setTranscribing(false);
      await generateSummaryFromText(text);
    } catch (e) {
      setTranscribing(false);
      throw e;
    }
  };

  const generateSessionTitle = async (transcriptText, summaryText) => {
    try {
      const lang = detectLanguage(transcriptText);
      const langNote = lang === 'ar' ? 'Write the title in Arabic.' : 'Write the title in English.';
      const result = await appClient.integrations.Core.InvokeLLM({
        prompt: `Based on the meeting transcript and summary below, generate a concise, descriptive title that represents the main topic of the meeting. The title should be:
- 3-8 words
- Descriptive and meaningful
- Professional and clear
- ${langNote}

Return only the title text, nothing else.

Transcript:
${transcriptText.slice(0, 1500)}

Summary:
${summaryText.slice(0, 1500)}`
      });
      const title = typeof result === "string" ? result.trim() : result;
      if (title && title.length > 0 && title.length < 100) {
        await appClient.entities.Session.update(sessionId, { title });
        return title;
      }
    } catch (e) {
      console.error("Title generation failed", e);
    }
    return null;
  };

  const checkTranscriptQuality = (text) => {
    if (!text) return 'empty';
    const trimmed = text.trim();
    const wordCount = trimmed.split(/\s+/).length;
    if (wordCount < 10) return 'empty';
    if (wordCount < 20) return 'insufficient';
    return null;
  };

// Auto-generate structured summary when transcript exists
// If summary exists but is plain bullets (not structured JSON), regenerate once.
const autoGeneratedRef = useRef(false);
const prevTranscriptRef = useRef(null);

const isStructuredSummary = (value) => {
  if (!value) return false;
  try {
    const parsed = typeof value === "string" ? JSON.parse(value) : value;
    return !!(
      parsed &&
      typeof parsed === "object" &&
      (
        Array.isArray(parsed.executive_summary) ||
        Array.isArray(parsed.key_discussions) ||
        Array.isArray(parsed.action_items)
      )
    );
  } catch {
    return false;
  }
};

useEffect(() => {
  // Reset when transcript changes
  if (transcript && transcript !== prevTranscriptRef.current) {
    prevTranscriptRef.current = transcript;
    autoGeneratedRef.current = false;
  }

  if (autoGeneratedRef.current) return;
  if (loading) return;
  if (!transcript || !transcript.trim()) return;

  // Wait until backend processing is done
  if (session?.processing_status === "pending" || session?.processing_status === "processing") return;

  const issue = checkTranscriptQuality(transcript);
  if (issue) return;

  // Only skip auto-generation if summary is already structured
  if (isStructuredSummary(summary)) return;

  autoGeneratedRef.current = true;
  // Use merged subsession transcript if available, else fall back to parent transcript
  getEffectiveTranscript().then(effectiveTranscript => {
    if (effectiveTranscript && effectiveTranscript.trim()) {
      generateSummaryFromText(effectiveTranscript);
    }
  });
}, [transcript, summary, loading, session?.processing_status, subsessions]);
    const handleRetranscribe = async () => {
    if (!audioUrl) return;
    setRetrying(true);
    try {
      const response = await appClient.functions.invoke('transcribeAudio', { audio_url: audioUrl });
      const text = response.data?.transcript;
      if (!text) throw new Error('No transcript returned');
      
      // Check new transcript quality
      const issue = checkTranscriptQuality(text);
      if (issue) {
        setQualityIssue(issue);
        setRetrying(false);
        return;
      }
      
      // Quality is good, save and generate summary
      await appClient.entities.Session.update(sessionId, { transcript_text: text });
      if (onTranscriptGenerated) onTranscriptGenerated(text);
      setQualityIssue(null);
      // Auto-generate summary
      await generateSummary();
    } catch (e) {
      console.error('Retranscribe failed:', e);
    } finally {
      setRetrying(false);
    }
  };

  const detectLanguage = (text) => {
    if (!text) return 'en';
    const arabicChars = (text.match(/[\u0600-\u06FF]/g) || []).length;
    const totalChars = text.replace(/\s/g, '').length;
    return (totalChars > 0 && arabicChars / totalChars > 0.3) ? 'ar' : 'en';
  };

  const getEffectiveTranscript = async () => {
    if (subsessions && subsessions.length > 0) {
      const merged = await buildMergedTranscript(subsessions);
      if (merged && merged.trim()) return merged;
    }
    return transcript;
  };

  const generateSummaryFromText = async (text) => {
    if (!text || !text.trim()) return;
    const issue = checkTranscriptQuality(text);
    if (issue) { setQualityIssue(issue); return; }
    setLoading(true);
    const lang = detectLanguage(text);

    // Build manual notes context to inject into prompt
    const notesContext = manualNotes && manualNotes.length > 0
      ? `\n\nIMPORTANT — Manual Notes Added During the Session:\n${manualNotes.map((n, i) => `${i + 1}. ${n}`).join('\n')}\nIncorporate these notes into the executive_summary, key_discussions, action_items, and next_steps where relevant.`
      : '';

    const langInstruction = lang === 'ar'
      ? 'CRITICAL: The transcript is in Arabic. You MUST write ALL text fields (executive_summary, key_discussions points, detailed_discussions content, decisions, action_items tasks, next_steps, risks, ai_insights, attendee roles and sample_quotes) entirely in Arabic. Do not use English anywhere in the output.'
      : 'Write all text fields in English.';
    try {
      const result = await appClient.integrations.Core.InvokeLLM({
        prompt: `You are an AI Meeting Intelligence Engine embedded in a mobile app called SILO.

${langInstruction}

Convert the transcript below into structured meeting minutes.${notesContext}
Return ONLY valid JSON matching this schema exactly:

{
  "attendees": [
    { "name": "Speaker Name or Speaker 1", "role": "inferred role or blank", "sample_quote": "a short representative quote from them" }
  ],
  "executive_summary": ["sentence 1", "sentence 2", "sentence 3", "sentence 4", "sentence 5"],
  "key_discussions": [
    { "title": "Theme Name", "points": ["detailed line 1", "detailed line 2", "detailed line 3", "detailed line 4", "detailed line 5"] }
  ],
  "detailed_discussions": [
    { "speaker": "Speaker Name or Speaker 1", "type": "stated|recommended|questioned|agreed|disagreed|suggested", "content": "paraphrase of what they said" }
  ],
  "decisions": ["decision 1"],
  "action_items": [
    { "task": "short task", "owner": "Owner", "deadline": "TBD", "priority": "High|Medium|Low", "status": "pending", "completed": false }
  ],
  "next_steps": ["step 1"],
  "risks": ["risk 1"],
  "ai_insights": ["insight 1"]
}

Rules:
- executive_summary: Write 4-6 complete sentences (50-200 words total) giving a thorough narrative overview of the meeting — what was discussed, key outcomes, tone, and any notable context. Each array item is one sentence.
- key_discussions: For each topic, write 4-5 detailed points (20-35 words each) that fully explain what was said, debated, and concluded on that topic. Do NOT write short one-liners.
- For attendees: extract real names if mentioned, otherwise use "Speaker 1", "Speaker 2", etc. Include a short sample quote for each.
- For detailed_discussions: list 8-15 key moments with who said what and the type (stated/recommended/questioned/agreed/disagreed/suggested)
- No markdown inside strings. Return ONLY the JSON object.
- Language rule: ${lang === 'ar' ? 'ALL output text MUST be in Arabic (العربية). This is mandatory.' : 'Write all output in English.'}

Transcript:
${text}`,
        response_json_schema: {
          type: "object",
          properties: {
            attendees: { type: "array", items: { type: "object", properties: { name: { type: "string" }, role: { type: "string" }, sample_quote: { type: "string" } } } },
            executive_summary: { type: "array", items: { type: "string" } },
            key_discussions: { type: "array", items: { type: "object", properties: { title: { type: "string" }, points: { type: "array", items: { type: "string" } } } } },
            detailed_discussions: { type: "array", items: { type: "object", properties: { speaker: { type: "string" }, type: { type: "string" }, content: { type: "string" } } } },
            decisions: { type: "array", items: { type: "string" } },
            action_items: { type: "array", items: { type: "object", properties: { task: { type: "string" }, owner: { type: "string" }, deadline: { type: "string" }, priority: { type: "string" }, status: { type: "string" }, completed: { type: "boolean" } } } },
            next_steps: { type: "array", items: { type: "string" } },
            risks: { type: "array", items: { type: "string" } },
            ai_insights: { type: "array", items: { type: "string" } }
          }
        }
      });
      const summaryStr = typeof result === "object" ? JSON.stringify(result) : result;
      // Save the original summary on first generation
      if (!originalSummary) {
        setOriginalSummary(summaryStr);
        await appClient.entities.Session.update(sessionId, { summary_text: summaryStr, original_summary_text: summaryStr });
      } else {
        await appClient.entities.Session.update(sessionId, { summary_text: summaryStr });
      }
      onSummaryGenerated(summaryStr);
      setQualityIssue(null);
      await Promise.all([
        generateSessionTitle(text, summaryStr),
        detectSessionType(text, summaryStr),
      ]);
    } catch (e) {
      console.error('Summary generation failed:', e);
    } finally {
      setLoading(false);
    }
  };

  const analyzeTranscriptPatterns = (text) => {
    if (!text) return {};
    
    // Count speakers and Q&A patterns
    const speakerMatches = [...text.matchAll(/\]\s*([^:]+):/g)];
    const speakers = [...new Set(speakerMatches.map(m => m[1].trim()))];
    
    // Count questions (lines ending with ?) vs statements
    const lines = text.split('\n');
    const questionLines = lines.filter(l => l.trim().endsWith('?')).length;
    const totalLines = lines.filter(l => l.trim().length > 0).length;
    const qaRatio = totalLines > 0 ? questionLines / totalLines : 0;
    
    // Detect job interview keywords
    const jobKeywords = /\b(experience|background|role|position|team|salary|benefits|responsibilities|strengths|weaknesses|project|achievement|growth|career|hire|candidate)\b/gi;
    const jobKeywordCount = (text.match(jobKeywords) || []).length;
    
    // Detect media interview Q&A pattern (alternating speakers, many questions)
    let alternatingCount = 0;
    for (let i = 0; i < speakerMatches.length - 1; i++) {
      if (speakerMatches[i][1].trim() !== speakerMatches[i + 1][1].trim()) {
        alternatingCount++;
      }
    }
    
    // Detect statement at beginning (long first turn before questions)
    const firstSpeakerFirstTurns = lines
      .slice(0, Math.min(50, lines.length))
      .filter(l => /\]\s*[^:]+:/.test(l))
      .slice(0, 2);
    const firstTurnLength = firstSpeakerFirstTurns.join('').length;
    
    return {
      speakerCount: speakers.length,
      speakers,
      qaRatio,
      jobKeywordCount,
      alternatingCount,
      firstTurnLength,
      questionLines,
      totalLines
    };
  };

  const detectSessionType = async (transcriptText, summaryText) => {
    try {
      const patterns = analyzeTranscriptPatterns(transcriptText);
      
      // Build enhanced prompt with pattern insights
      let prompt = `Based on the meeting transcript and summary below, classify this session into exactly ONE of these types:
Meeting, Lecture, Workshop, Class, Idea, Brainstorm, Strategy, Media interview, Job interview, Press Conference

Definitions:
- Meeting: general discussion between multiple people, status updates, coordination
- Lecture: one person teaching or presenting information to others
- Workshop: hands-on collaborative session with exercises or activities
- Class: educational session with students, structured curriculum
- Idea: early-stage idea exploration or pitch, one or few people
- Brainstorm: free-form idea generation, creative session with multiple participants
- Strategy: planning, decision-making, roadmap or goal-setting session
- Media interview: conversation between 2 speakers with Q&A pattern - one interviewer asks questions, the other replies. Has alternating speakers and high Q&A ratio.
- Job interview: one-on-one or small group discussion focused on job/career questions about experience, background, role, responsibilities, candidate fit, skills assessment.
- Press Conference: one main speaker gives an opening statement, then takes questions from multiple reporters/audience members. Starts with a statement, followed by Q&A from many speakers.

Pattern analysis hints:
- Speaker count: ${patterns.speakerCount}
- Q&A ratio: ${(patterns.qaRatio * 100).toFixed(1)}% of lines are questions
- Job-related keywords: ${patterns.jobKeywordCount}
- Speaker alternations: ${patterns.alternatingCount}
- Opening statement length: ${patterns.firstTurnLength} chars

Return ONLY the type name, nothing else.

Transcript: ${transcriptText.slice(0, 2500)}
Summary: ${summaryText.slice(0, 1000)}`;

      const result = await appClient.integrations.Core.InvokeLLM({ prompt });
      const type = typeof result === "string" ? result.trim() : null;
      const valid = ["Meeting","Lecture","Workshop","Class","Idea","Brainstorm","Strategy","Media interview","Job interview","Press Conference"];
      if (type && valid.includes(type)) {
        await appClient.entities.Session.update(sessionId, { session_type: type });
      }
    } catch (e) {
      console.error("Session type detection failed", e);
    }
  };

  const generateSummary = async () => {
    const effectiveTranscript = await getEffectiveTranscript();
    if (!effectiveTranscript || !effectiveTranscript.trim()) return;
    await generateSummaryFromText(effectiveTranscript);
  };

  const handleRegenerateClick = () => {
    setShowRegenerationWarning(true);
  };

  const handleConfirmRegenerate = async () => {
    setShowRegenerationWarning(false);
    await generateSummary();
  };



  if (transcribing) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <Loader2 className="w-6 h-6 text-gray-400 animate-spin mb-3" />
        <p className="text-sm text-gray-400">Transcribing audio...</p>
      </div>
    );
  }

  if (!summary && !loading) {
    const hasLiveTranscript = transcript && transcript.trim().length > 0;
    const wordCount = hasLiveTranscript ? transcript.split(/\s+/).filter(w => w).length : 0;
    const transcriptQualityWarning = hasLiveTranscript && wordCount < 20;

    return (
      <div className="space-y-3">
        {qualityIssue && (
          <TranscriptQualityWarning
            issue={qualityIssue}
            isRetranscribing={retrying}
            onRetranscribe={handleRetranscribe}
            onDismiss={() => setQualityIssue(null)}
          />
        )}
        {transcriptQualityWarning && (
          <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/30">
            <p className="text-xs text-amber-600 dark:text-amber-300">
              <span className="font-semibold">⚠️ Live transcript captured only {wordCount} words.</span> This may indicate the live transcription wasn't working (especially with system audio). Try re-transcribing with Whisper below.
            </p>
          </div>
        )}
        {audioUrl && (
          <div className="text-center py-4 border border-dashed border-gray-200 dark:border-[#3A3A3C] rounded-xl">
            {(() => {
              const isProcessing = session?.processing_status === 'processing' || session?.assemblyai_job_id;
              if (!transcript) {
                return (
                  <>
                    <p className="text-sm text-gray-400 dark:text-[#A1A1A6] mb-3">
                      {isProcessing ? 'Transcription in progress...' : 'No transcript yet — generate one from the audio'}
                    </p>
                    <Button
                      onClick={transcribeAudio}
                      disabled={!!isProcessing}
                      variant="outline"
                      className="rounded-full px-6 gap-2 text-gray-600 dark:text-[#A1A1A6] dark:border-[#3A3A3C] dark:hover:bg-[#2C2C2E]"
                    >
                      {isProcessing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Mic className="w-4 h-4" />}
                      {isProcessing ? 'Processing...' : 'Transcribe Audio'}
                    </Button>
                  </>
                );
              }
              return (
                <>
                  <p className="text-sm text-gray-400 dark:text-[#A1A1A6] mb-3">
                    {transcriptQualityWarning ? 'Try re-transcribing with Whisper' : 'Audio has been transcribed'}
                  </p>
                  <div className="flex gap-2 items-center justify-center flex-wrap">
                    {transcriptQualityWarning && (
                      <Button
                        onClick={handleRetranscribe}
                        disabled={retrying || !!isProcessing}
                        variant="outline"
                        className="rounded-full px-6 gap-2 text-purple-600 dark:text-purple-400 border-purple-300 dark:border-purple-500/30 dark:hover:bg-purple-500/10"
                      >
                        {retrying ? <Loader2 className="w-4 h-4 animate-spin" /> : <Mic className="w-4 h-4" />}
                        Re-transcribe with Whisper
                      </Button>
                    )}
                    <Button
                      onClick={() => document.querySelector('[data-transcript-editor]')?.scrollIntoView({ behavior: 'smooth' })}
                      variant="outline"
                      className="rounded-full px-6 gap-2 text-gray-600 dark:text-[#A1A1A6] dark:border-[#3A3A3C] dark:hover:bg-[#2C2C2E]"
                    >
                      <Mic className="w-4 h-4" />
                      View Transcript
                    </Button>
                  </div>
                </>
              );
            })()}
          </div>
        )}
        <div className="text-center py-6">
          <div className="w-12 h-12 rounded-full bg-gray-100 dark:bg-[#1C1C1E] flex items-center justify-center mx-auto mb-4">
            <Sparkles className="w-5 h-5 text-gray-400" />
          </div>
          <p className="text-sm text-gray-400 dark:text-[#A1A1A6] mb-4">
            Generate an AI summary of this session
          </p>
          <Button
            onClick={generateSummary}
            disabled={!transcript || retrying}
            className="bg-gray-900 dark:bg-white dark:text-gray-900 hover:bg-gray-800 dark:hover:bg-gray-100 text-white rounded-full px-6"
          >
            {retrying ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
            Generate Summary
          </Button>
          {!transcript && (
            <p className="text-xs text-gray-300 dark:text-[#48484A] mt-2">Transcribe audio first to generate a summary</p>
          )}
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <Loader2 className="w-6 h-6 text-gray-400 animate-spin mb-3" />
        <p className="text-sm text-gray-400">Generating summary...</p>
      </div>
    );
  }

  let parsed = null;
  try { parsed = typeof summary === "string" ? JSON.parse(summary) : summary; } catch (e) { parsed = null; }

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-gray-900 dark:text-white uppercase tracking-wider">
          Summary
        </h3>
        <div className="flex items-center gap-1">
          <ExportShare session={session} summaryData={parsed} />
          <Button
            variant="ghost"
            size="sm"
            onClick={handleRegenerateClick}
            className="text-xs text-gray-400 hover:text-gray-600 gap-1.5"
          >
            <RefreshCw className="w-3 h-3" />
            Regenerate
          </Button>
        </div>
      </div>
      <StructuredMinutes
        data={parsed}
        audioUrl={audioUrl}
        transcript={transcript}
        originalSummary={originalSummary}
        onDataChange={async (updatedData) => {
          const newText = JSON.stringify(updatedData);
          await appClient.entities.Session.update(sessionId, { summary_text: newText });
          if (onSummaryGenerated) onSummaryGenerated(newText);
        }}
        onRestoreOriginal={async () => {
          if (originalSummary) {
            await appClient.entities.Session.update(sessionId, { summary_text: originalSummary });
            if (onSummaryGenerated) onSummaryGenerated(originalSummary);
          }
        }}
      />
      <RegenerationWarningDialog
        isOpen={showRegenerationWarning}
        onConfirm={handleConfirmRegenerate}
        onCancel={() => setShowRegenerationWarning(false)}
        isLoading={loading}
      />
    </div>
  );
}